title: Ayush Parwal
logo: /assets/img/tomcat-sleep.jpg
description: "Machine Learning, AI Researcher with a passion for Search Engines and Natural Language Processing."
theme: jekyll-theme-cayman-dark
